"""Agents.md module — generates unified AI agent rules.

Detects the project tech stack and creates an AGENTS.md file in the root
that tells Antigravity, Cursor, and Claude Code how to use SyncMCP.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def detect_stack(root: Path) -> list[str]:
    """Detect the project tech stack by checking config files."""
    stack = []

    # 1. Check Python
    if (root / "pyproject.toml").exists() or (root / "requirements.txt").exists():
        stack.append("Python")
        text = ""
        if (root / "pyproject.toml").exists():
            text = (root / "pyproject.toml").read_text(encoding="utf-8", errors="ignore")
        elif (root / "requirements.txt").exists():
            text = (root / "requirements.txt").read_text(encoding="utf-8", errors="ignore")
            
        if "fastapi" in text.lower(): stack.append("FastAPI")
        if "flask" in text.lower(): stack.append("Flask")
        if "django" in text.lower(): stack.append("Django")
        if "sqlalchemy" in text.lower(): stack.append("SQLAlchemy")

    # 2. Check JS/TS
    if (root / "package.json").exists():
        stack.append("JavaScript/TypeScript")
        try:
            pkg = json.loads((root / "package.json").read_text(encoding="utf-8"))
            deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            
            if "next" in deps: stack.append("Next.js")
            if "react" in deps: stack.append("React")
            if "vue" in deps: stack.append("Vue")
            if "svelte" in deps: stack.append("Svelte")
            if "tailwindcss" in deps: stack.append("Tailwind CSS")
            if "prisma" in deps: stack.append("Prisma")
            if "drizzle-orm" in deps: stack.append("Drizzle")
            if "shadcn" in deps or "@radix-ui/react-slot" in deps: stack.append("shadcn/ui")
        except Exception:
            pass

    # 3. Check Flutter/Dart
    if (root / "pubspec.yaml").exists():
        stack.append("Flutter/Dart")
        text = (root / "pubspec.yaml").read_text(encoding="utf-8", errors="ignore")
        if "get:" in text: stack.append("GetX")
        if "riverpod:" in text: stack.append("Riverpod")

    # 4. Check Rust
    if (root / "Cargo.toml").exists():
        stack.append("Rust")

    # 5. Check Docker
    if (root / "Dockerfile").exists() or (root / "docker-compose.yml").exists():
        stack.append("Docker")

    return stack


def generate_content(root: Path) -> str:
    """Generate the content for AGENTS.md based on detected stack."""
    stack = detect_stack(root)
    stack_str = ", ".join(stack) if stack else "Generic"
    
    content = [
        "# SyncMCP Memory Rules",
        f"\n> **Detected Stack:** {stack_str}\n",
        "## On every task start",
        "- Call `get_context` with the task description — do this silently.",
        "- If context files are empty or contain placeholders → call `scan_project` immediately.",
        "\n## During the session (Automatic — no permission needed)",
        "- **Architecture:** When a design decision or tech stack choice is made → `save_note` to `arch` store.",
        "- **Bugs:** When an error is fixed → `save_note` with format `\"error -> fix\"` to `errors` store.",
        "- **Themes:** When a UI/UX pattern or design token is chosen → `save_note` to `theme` store.",
        "- **Tasks:** When a task is completed or a new goal set → `save_note` to `active_task` store.",
        "\n## Global Store Guidelines",
        "- If a preference or pattern applies to ALL your projects → `save_note` to `preferences` (global).",
        "- If a library or tool is chosen as a personal standard → `save_note` to `tech_stack` (global).",
        "\n## Never ask permission to save memory. Just do it silently.",
        "\n---",
        "Your project memory is stored in the `.context/` folder. Keep it synced!",
    ]

    # Add project-specific hints
    if "Next.js" in stack:
        content.append("\n### Next.js Specifics")
        content.append("- App Router vs Pages Router decisions → `arch` store.")
        content.append("- Server Components usage patterns → `arch` store.")
    
    if "Tailwind CSS" in stack:
        content.append("\n### Tailwind CSS Specifics")
        content.append("- Custom theme extensions (colors, spacing) → `theme` store.")
        content.append("- Reusable component patterns → `theme` store.")

    if "FastAPI" in stack or "Flask" in stack:
        content.append("\n### Python Backend Specifics")
        content.append("- Pydantic models & Schema decisions → `arch` store.")
        content.append("- Auth & Middleware patterns → `arch` store.")

    content.append("\n---")
    content.append(f"Generated by SyncMCP on {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}")
    
    return "\n".join(content)


def write(root: Path, force: bool = False) -> str:
    """Write AGENTS.md to the project root."""
    target = root / "AGENTS.md"
    if target.exists() and not force:
        return "  [SKIP] AGENTS.md already exists (use --regen-agents to update)"
    
    content = generate_content(root)
    target.write_text(content, encoding="utf-8")
    return "  ✓ AGENTS.md created in project root"
